# Generated by Django 3.1.5 on 2021-02-06 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210203_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_byuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liked_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
