# Generated by Django 3.1.5 on 2021-02-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210206_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='like_byuser',
            new_name='like_by',
        ),
    ]
