# Generated by Django 3.1.5 on 2021-02-06 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210206_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_topost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='network.post', to_field='title'),
        ),
    ]
