# Generated by Django 3.1.5 on 2021-02-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210206_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_by',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
